# Generated by Django 3.0.8 on 2020-07-03 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityperiod',
            name='user',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, to='members.User'),
            preserve_default=False,
        ),
    ]
