# Generated by Django 3.0.8 on 2020-07-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_activityperiod_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='Default_User', max_length=10),
            preserve_default=False,
        ),
    ]
