# Generated by Django 3.0.8 on 2020-07-04 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20200704_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityperiod',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user',
            name='activity_periods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.ActivityPeriod'),
        ),
        migrations.AlterField(
            model_name='activityperiod',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
